#!/usr/bin/env python
from django.core.management import setup_environ
from kgreg.conf import settings
setup_environ(settings)

from django.core.management import execute_manager
if __name__ == "__main__":
    execute_manager(settings)
