#!/bin/bash
set -e

#DEBHELPER#

if [ "$1" = "configure" ]; then
    if [ ! -d "/var/lib/karaage-registration/static" ]; then
        python2.7 /usr/lib/python2.7/dist-packages/django/bin/django-admin.py \
            collectstatic --settings=kgreg.conf.settings --noinput
    fi
fi

if [ "$1" = "triggered" ]; then
    if [ "$2" = "karaage-static" ]; then
        python2.7 /usr/lib/python2.7/dist-packages/django/bin/django-admin.py \
            collectstatic --settings=kgreg.conf.settings --noinput
    fi
fi
